In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math

In [ ]:
def movement(direction):
    #1 - North
    #2 - North-East
    #3 - East
    #.....
    #8 - North-West
    mov_x = 0
    mov_y = 0
    if direction == 1:
        mov_y = 1
    elif direction == 2:
        mov_x = 1
        mov_y = 1
    elif direction == 3:
        mov_x = 1
    elif direction == 4:
        mov_x = 1
        mov_y = -1
    elif direction == 5:
        mov_y = -1
    elif direction == 6:
        mov_x = -1
        mov_y = -1
    elif direction == 7:
        mov_x = -1
    else:
        mov_x = -1
        mov_y = 1
    return mov_x,mov_y    


def canMove(posX,posY,movX,movY,map):
    ans = False
    posX1 = posX + movX
    posY1 = posY + movY
    if map[posX1,posY1] != 0:
        ans = True
    return ans



def randomPath(maxTime,minTimePP,maxTimePP,size,flightAltitude,posArrayInitial):
    time_array = np.array([],dtype=np.int16)
    flagTime = False
    
    while not flagTime:
        num = int(random.uniform(minTimePP,maxTimePP))
        if time_array.sum()+num >= maxTime:
            flagTime = True 
        else:
            time_array = np.append(time_array,num)

    posX,posY = posArrayInitial
    
    #Create the Map/Grid
    baseArray_path = np.ones((size,size))
    baseArray_path = np.pad(baseArray_path,pad_width=1)

    flag = False

    while not flag:
        #Decide the direction
        dir = random.randint(1,8)
        movX,movY = movement(dir)

        #Can move in that direction?
        flagMove = canMove(posX,posY,movX,movY,baseArray_path)
        contMove = 0
        while contMove <= size/2 and flagMove:
            #Move
            posX += movX
            posY += movY
            #Upload Map/Grid 
            baseArray_path[posX,posY] = 0

            #Can continue move in that direction?
            flagMove = canMove(posX,posY,movX,movY,baseArray_path)
            contMove += 1
        

    return baseArray_path


    

## RandomPath function
 **'randomPath' only create one path.**
- maxTime = maximum time of one execution.
- minTimePP = minimum random time between two points of the path.
- maxTimePP = maximum random time between two points of the path.
- sizeH = Height - maximum value.
- sizeW = Width - maximum value.
    - the grid has a height interval of [-sizeH,sizeH] and a Width interval of [-sizeW,sizeW]
- flightAltitude = Flight altitude.
- posArrayInitial = Initial position index.

In [3]:
def comparison(numInitial,numFinal):
    sum = 0
    if numInitial > numFinal:
        sum = -1
    elif numInitial < numFinal:
        sum = 1
    return sum


def putLine(initIdx,finalIdx,matrix):
    
    #print(initIdx)
    #print(finalIdx)

    x_init = initIdx[0]
    y_init = initIdx[1]
    x_final = finalIdx[0]
    y_final = finalIdx[1]

    coor = np.array([initIdx])
    sum_x = comparison(x_init,x_final)
    sum_y = comparison(y_init,y_final)

    cont = 0

    while np.all(coor[-1,:]!=finalIdx) and cont <= 5:
        x = x_init + sum_x
        y = y_init + sum_y
        coor = np.append(coor,[[x,y]],axis=0)
        x_init = x
        y_init = y
        cont += 1
    
    #print(coor)

    for i in coor:
        matrix[i[0],i[1]] = 0
        
    return matrix,coor.tolist()


In [55]:
def randomPath(maxTime,minTimePP,maxTimePP,sizeH,sizeW,flightAltitude,posArrayInitial):
    time_array = np.array([],dtype=np.int16)
    flagTime = False
    
    while not flagTime:
        num = int(random.uniform(minTimePP,maxTimePP))
        if time_array.sum()+num >= maxTime:
            flagTime = True 
        else:
            time_array = np.append(time_array,num)
    
    baseArray_path = np.ones((sizeH*2+1,sizeW*2+1))
    flagIdx = False
    pathArray = []
    cont = 0
    x_idx = posArrayInitial[0]
    y_idx = posArrayInitial[1]
    pathArray.append([x_idx,y_idx,flightAltitude])
    #baseArray_path[x_idx,y_idx] = 0
    
    while not np.all(baseArray_path == 0) and cont < time_array.shape[0]-1:
        
        while not flagIdx:
            x_dir = random.randint(-1,1)
            y_dir = random.randint(-1,1)
            
            try:
                x_idx_1 = x_idx + x_dir
                y_idx_1 = y_idx + y_dir
                baseArray_path[x_idx,y_idx]
            except IndexError:
                continue
            
            if x_idx_1 >= 0 and y_idx_1 >= 0:
                x_idx = x_idx_1
                y_idx = y_idx_1
                x_idx_1 = 0
                y_idx_1 = 0

            if baseArray_path[x_idx,y_idx] == 1 and x_idx-sizeW != pathArray[cont][0] and y_idx-sizeH != pathArray[cont][1]:
                flagIdx = True
                pathArray.append([x_idx-sizeW,y_idx-sizeH,flightAltitude])
                #baseArray_path[x_idx,y_idx] = 0
                
            else:
                continue
        
        flagIdx = False
        cont+=1
    return baseArray_path,np.array(pathArray),time_array

mapa,path,time = randomPath(700,40,80,2,2,1,[0,0])          

In [152]:
coor = []
coorD = [[2,1],[3,1]]
[coor.append(i) for i in coorD]
print(coor)

[[2, 1], [3, 1]]


In [159]:
np.all([2,1] in coorD)

True

In [57]:
path

array([[ 0,  0,  1],
       [-1, -2,  1],
       [-2, -1,  1],
       [-3, -2,  1],
       [-4, -4,  1],
       [-3, -6,  1],
       [-4, -5,  1],
       [-6, -6,  1],
       [-7, -5,  1],
       [-5, -6,  1],
       [-6, -5,  1],
       [-7, -4,  1]])

In [14]:
sizeH = 5
sizeW = 5
baseArray_path = np.ones((sizeH*2+1,sizeW*2+1))
print(baseArray_path)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
totalBaseArray_path = np.ones((sizeH*2+2,sizeW*2+2))
idxH,idxW = totalBaseArray_path.shape
print(idxH,idxW)

12 12


In [15]:
baseArray_path = np.pad(baseArray_path,pad_width=2)
print(baseArray_path)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [114]:
test_matrix = np.ones((5,5))
matrix,coor = putLine([3,0],[3,4],test_matrix)

In [115]:
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [120]:
coor

array([[3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4]])

In [127]:
np.any([[3,0],[0,0]] == coor)

False

In [143]:
cosa = np.intersect1d([[3,0],[0,0]],coor)
cosa

array([0, 3])

In [124]:
[3,0] in coor

True

In [126]:
[[3,0],[0,0]] == coor

False